export { ShiftPanel } from "./panels/·-Shift-board-panel";
export { RoundsPanel } from "./panels/·-My-patients-panel";
export { UnknownPanel } from "./panels/·-Clinic-list-panel";
export { ClinicPanel } from "./panels/·-Clinic-list-panel";
export { ResultsPanel } from "./panels/·-Results-inbox-panel";
export { OrdersPanel } from "./panels/·-Orders-&-meds-panel";
export { NotesPanel } from "./panels/·-Documentation-panel";
export { HandoverPanel } from "./panels/·-Handover-panel";
export { RotaPanel } from "./panels/·-Rota-panel";